server:
  port: 8091
spring:
  application:
    name: memo-prod
  config:
    import:
      - nacos:${spring.application.name}?group=DEFAULT_GROUP&namespace=3bab571d-f90f-4486-bdca-60d26a3bca22
  nacos:
    config:
      server-addr: mikuyun-nacos-standalone:8880
      file-extension: yaml