spring:
  application:
    name: mikuyun-admin

---
spring:
  config:
    activate:
      on-profile: local
    import:
      - nacos:${spring.application.name}-local?group=DEFAULT_GROUP
  nacos:
    config:
      namespace: 3bab571d-f90f-4486-bdca-60d26a3bca22
      server-addr: 127.0.0.1:8848
      file-extension: yaml

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - nacos:${spring.application.name}-prod?group=DEFAULT_GROUP
  nacos:
    config:
      namespace: e0d7ece3-9ea3-4690-bf60-a9debdcc0c5a
      server-addr: mikuyun-nacos-standalone:8848
      file-extension: yaml