######## server配置
server:
  port: 8091
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml
springdoc:
  swagger-ui:
    enabled: false
######## Sa-Token (文档地址: https://sa-token.cc)
sa-token:
  # token名称
  token-name: Authorization
  # token过期时间
  timeout: 640800
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 操作日志
  is-log: true
  token-prefix: Bearer
  token-session-check-login: false

######## spring配置
spring:
  env: prod
  servlet:
    multipart:
      maxFileSize: 30MB
      maxRequestSize: 100MB
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mikuyun
    url: jdbc:mysql://1Panel-mysql-jlRD:3306/mikuyun?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  data:
    redis:
      # Redis数据库索引（默认为0）
      database: 2
      # Redis服务器地址
      host: 1Panel-redis-CJrQ
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password: mikuyun
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
  # 邮箱服务
  mail:
    host: smtp.163.com
    # 发件人昵称
    nickname: mikuyun
    # 邮箱账户
    username: mikuyun_sendonly@163.com
    # 邮箱第三方授权码
    password: KNYDAMGUCKCPKHUM
    # 编码类型
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: rue
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

######## 日志配置
logging:
  config: classpath:logback.xml
  level:
    com.xxl.job.core.server.EmbedServer: off

######## mybatis-plus配置控制台打印完整带参数SQL语句
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

######## xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    enabled: true
    executor:
      # 执行器 AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      address:
      # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip:
      # 执行器 AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: mikuyun-admin-executor
      # 执行器端口号
      port: 18091
      # xxl-job executor log-path
      logpath: /data/applogs/xxl-job/job
      # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 30
    admin:
      # 调度中心地址
      addresses: http://xxl-job-admin:8089/xxl-job-admin
      accessToken: hatsune_miku
      timeout: 3

######## rocketMQ配置
rocketmq:
  nameServer: rocketmq-mikuyun-rmqnamesrv:9876
  groupName: mikuyun-admin
  consumeThread: 16

######## minio配置
minio:
  endpoint: http://minio-mikuyun:9000
  access-key: NhQlOFYcyXiQm40DpW56
  secret-key: O1q6YRp79cTeNrtHT8yHXgcFWcOTDJNpKpRsYMzp
  bucket-name: mikuyun

######## 系统默认加密盐
qiseyun:
  salt: mikuyun
  userSalt: mikuyun_user

######## excel任务并行数
excelTask:
  normalRate: 5
  slowRate: 1