create table mk_captcha
(
    id              integer generated by default as identity,
    account         text      default ''::text          not null,
    captcha_str     text                                not null,
    captcha_type    smallint  default 0                 not null,
    gmt_created     timestamp default CURRENT_TIMESTAMP not null,
    expiration_time timestamp                           not null
);

comment on column mk_captcha.id is '主键';

comment on column mk_captcha.account is '账号';

comment on column mk_captcha.captcha_str is '验证码';

comment on column mk_captcha.captcha_type is '验证码类型1短信,2邮件';

comment on column mk_captcha.gmt_created is '创建时间';

comment on column mk_captcha.expiration_time is '过期时间';

alter table mk_captcha
    owner to postgres;

create table mk_excel_task
(
    id               integer,
    param            json,
    file_name        text,
    operation_ip     text,
    task_start_time  timestamp,
    task_finish_time timestamp,
    excel_type       integer,
    download_url     text,
    status           integer   default 0                 not null,
    gmt_created      timestamp default CURRENT_TIMESTAMP not null,
    gmt_modified     timestamp,
    create_by        integer   default 0                 not null,
    update_by        integer   default 0                 not null,
    is_delete        smallint  default 0                 not null
);

comment on column mk_excel_task.param is '查询参数json格式';

comment on column mk_excel_task.file_name is '文件名';

comment on column mk_excel_task.operation_ip is '操作ip';

comment on column mk_excel_task.task_start_time is '导出开始时间';

comment on column mk_excel_task.task_finish_time is '导出完成时间';

comment on column mk_excel_task.excel_type is '导出类型(1示例)';

comment on column mk_excel_task.download_url is '下载地址';

comment on column mk_excel_task.status is '状态(0未开始,1已完成)';

comment on column mk_excel_task.gmt_created is '创建时间';

comment on column mk_excel_task.gmt_modified is '修改时间';

comment on column mk_excel_task.create_by is '创建人';

comment on column mk_excel_task.update_by is '修改人';

comment on column mk_excel_task.is_delete is '是否删除1已删除0未删除';

alter table mk_excel_task
    owner to postgres;

create table mk_sys_config
(
    id           serial
        primary key,
    config_name  text                                not null,
    config_key   text                                not null
        constraint uk_mk_sys_config_config_key
            unique,
    config_value text                                not null,
    is_lock      smallint  default 0,
    remark       text,
    gmt_created  timestamp default CURRENT_TIMESTAMP not null,
    gmt_modified timestamp default CURRENT_TIMESTAMP not null,
    create_by    integer   default 0                 not null,
    update_by    integer   default 0                 not null,
    is_delete    smallint  default 0                 not null
);

comment on table mk_sys_config is '参数配置表';

comment on column mk_sys_config.id is '参数配置ID';

comment on column mk_sys_config.config_name is '参数名';

comment on column mk_sys_config.config_key is '参数key';

comment on column mk_sys_config.config_value is '参数value';

comment on column mk_sys_config.is_lock is '是否锁定';

comment on column mk_sys_config.remark is '备注';

comment on column mk_sys_config.gmt_created is '创建时间';

comment on column mk_sys_config.gmt_modified is '修改时间';

comment on column mk_sys_config.create_by is '创建人id';

comment on column mk_sys_config.update_by is '更新人id';

comment on column mk_sys_config.is_delete is '0：正常 1：删除';

alter table mk_sys_config
    owner to postgres;

create table mk_sys_dict
(
    id               integer                             not null
        primary key,
    sys_dict_type_id bigint                              not null,
    enum_name        text                                not null,
    enum_code        text                                not null,
    sort             integer                             not null,
    remark           text      default ''::text          not null,
    is_lock          smallint  default 0                 not null,
    gmt_created      timestamp default CURRENT_TIMESTAMP not null,
    gmt_modified     timestamp default CURRENT_TIMESTAMP not null,
    create_by        integer   default 0                 not null,
    update_by        integer   default 0                 not null,
    is_delete        smallint  default 0                 not null
);

comment on table mk_sys_dict is '字典表';

comment on column mk_sys_dict.id is '字典ID(规则)';

comment on column mk_sys_dict.sys_dict_type_id is '关联sys_dict_type ID';

comment on column mk_sys_dict.enum_name is '字典枚举名称';

comment on column mk_sys_dict.enum_code is '字典枚举值';

comment on column mk_sys_dict.sort is '排序(正序)';

comment on column mk_sys_dict.remark is '备注';

comment on column mk_sys_dict.is_lock is '是否锁定';

comment on column mk_sys_dict.gmt_created is '创建时间';

comment on column mk_sys_dict.gmt_modified is '修改时间';

comment on column mk_sys_dict.create_by is '创建人id';

comment on column mk_sys_dict.update_by is '更新人id';

comment on column mk_sys_dict.is_delete is '0：正常 1：删除';

alter table mk_sys_dict
    owner to postgres;

create table mk_sys_dict_type
(
    id           serial
        primary key,
    type_name    text      default ''::text          not null,
    type_code    text                                not null,
    is_lock      smallint  default 0,
    remark       text      default ''::text,
    gmt_created  timestamp default CURRENT_TIMESTAMP not null,
    gmt_modified timestamp default CURRENT_TIMESTAMP not null,
    create_by    integer   default 0                 not null,
    update_by    integer   default 0                 not null,
    is_delete    smallint  default 0                 not null
);

comment on table mk_sys_dict_type is '字典类型';

comment on column mk_sys_dict_type.id is '字典类型ID';

comment on column mk_sys_dict_type.type_name is '字典类型名(中文)';

comment on column mk_sys_dict_type.type_code is '字典类型码(英文)';

comment on column mk_sys_dict_type.is_lock is '是否锁定，锁定的属性无法在页面进行修改';

comment on column mk_sys_dict_type.remark is '描述';

comment on column mk_sys_dict_type.gmt_created is '创建时间';

comment on column mk_sys_dict_type.gmt_modified is '修改时间';

comment on column mk_sys_dict_type.create_by is '创建人id';

comment on column mk_sys_dict_type.update_by is '更新人id';

comment on column mk_sys_dict_type.is_delete is '0：正常 1：删除';

alter table mk_sys_dict_type
    owner to postgres;

create table mk_sys_file
(
    id             serial
        primary key,
    channel        text      default ''::text          not null,
    original_name  text                                not null,
    type           text      default ''::text          not null,
    md5            text                                not null,
    file_ext       text      default ''::text          not null,
    url            text      default ''::text          not null,
    file_size_byte bigint    default 0                 not null,
    gmt_created    timestamp default CURRENT_TIMESTAMP not null
);

comment on table mk_sys_file is '文件表';

comment on column mk_sys_file.id is 'id';

comment on column mk_sys_file.channel is '存储渠道';

comment on column mk_sys_file.original_name is '原始名称';

comment on column mk_sys_file.type is '文件类型';

comment on column mk_sys_file.md5 is '文件MD5';

comment on column mk_sys_file.file_ext is '文件格式';

comment on column mk_sys_file.url is '文件地址';

comment on column mk_sys_file.file_size_byte is '文件大小(byte)';

comment on column mk_sys_file.gmt_created is '创建时间';

alter table mk_sys_file
    owner to postgres;

create index idx_mk_sys_file_channel_type
    on mk_sys_file (channel, type);

create index idx_mk_sys_file_gmt_created
    on mk_sys_file (gmt_created);

create index idx_mk_sys_file_md5
    on mk_sys_file (md5);

create table mk_sys_permissions
(
    id           serial
        primary key,
    name         text      default ''::text          not null,
    permission   text      default ''::text          not null,
    parent_id    integer   default 0                 not null,
    keep_alive   smallint  default 0                 not null,
    type         smallint  default 0                 not null,
    describe     text      default ''::text          not null,
    gmt_created  timestamp default CURRENT_TIMESTAMP not null,
    gmt_modified timestamp default CURRENT_TIMESTAMP not null,
    create_by    integer   default 0                 not null,
    update_by    integer   default 0                 not null,
    is_delete    smallint  default 0                 not null
);

comment on table mk_sys_permissions is '系统菜单组件权限';

comment on column mk_sys_permissions.id is '菜单ID';

comment on column mk_sys_permissions.name is '名称';

comment on column mk_sys_permissions.permission is '权限标识';

comment on column mk_sys_permissions.parent_id is '父菜单ID';

comment on column mk_sys_permissions.keep_alive is '0-开启，1- 关闭';

comment on column mk_sys_permissions.type is '菜单类型 （-1根节点 0页面 1组件 2接口）';

comment on column mk_sys_permissions.describe is '描述';

comment on column mk_sys_permissions.gmt_created is '创建时间';

comment on column mk_sys_permissions.gmt_modified is '修改时间';

comment on column mk_sys_permissions.create_by is '创建人id';

comment on column mk_sys_permissions.update_by is '更新人id';

comment on column mk_sys_permissions.is_delete is '0：正常 1：删除';

alter table mk_sys_permissions
    owner to postgres;

create table mk_sys_role
(
    id           serial
        primary key,
    role_name    text      default ''::text          not null,
    role_code    text      default ''::text          not null
        constraint uk_mk_sys_role_role_code
            unique,
    role_desc    text      default ''::text          not null,
    gmt_created  timestamp default CURRENT_TIMESTAMP not null,
    gmt_modified timestamp default CURRENT_TIMESTAMP not null,
    create_by    integer   default 0                 not null,
    update_by    integer   default 0                 not null,
    is_delete    smallint  default 0                 not null
);

comment on table mk_sys_role is '系统角色表';

comment on column mk_sys_role.role_name is '角色名称';

comment on column mk_sys_role.role_code is '唯一code';

comment on column mk_sys_role.role_desc is '描述';

comment on column mk_sys_role.gmt_created is '创建时间';

comment on column mk_sys_role.gmt_modified is '修改时间';

comment on column mk_sys_role.create_by is '创建人id';

comment on column mk_sys_role.update_by is '更新人id';

comment on column mk_sys_role.is_delete is '0：正常 1：删除';

alter table mk_sys_role
    owner to postgres;

create table mk_sys_role_permissions
(
    role_id       integer not null,
    permission_id integer not null,
    primary key (permission_id, role_id)
);

comment on table mk_sys_role_permissions is '角色菜单表';

comment on column mk_sys_role_permissions.role_id is '角色ID';

comment on column mk_sys_role_permissions.permission_id is '菜单ID';

alter table mk_sys_role_permissions
    owner to postgres;

create table mk_sys_user
(
    id           serial
        primary key,
    username     text      default ''::text          not null,
    password     text      default ''::text          not null,
    real_name    text      default ''::text          not null,
    salt         text      default ''::text          not null,
    phone        text      default ''::text          not null,
    avatar       text      default ''::text          not null,
    dept_id      integer   default 0                 not null,
    lock_flag    smallint  default 0                 not null,
    email        text      default ''::text          not null,
    gmt_created  timestamp default CURRENT_TIMESTAMP not null,
    gmt_modified timestamp default CURRENT_TIMESTAMP not null,
    create_by    integer   default 0                 not null,
    update_by    integer   default 0                 not null,
    is_delete    smallint  default 0                 not null
);

comment on table mk_sys_user is '用户表';

comment on column mk_sys_user.id is '主键ID';

comment on column mk_sys_user.username is '用户名';

comment on column mk_sys_user.password is '密码';

comment on column mk_sys_user.real_name is '真实姓名';

comment on column mk_sys_user.salt is '随机盐';

comment on column mk_sys_user.phone is '手机号';

comment on column mk_sys_user.avatar is '头像';

comment on column mk_sys_user.dept_id is '部门ID';

comment on column mk_sys_user.lock_flag is '0-正常，9-锁定';

comment on column mk_sys_user.email is '邮箱';

comment on column mk_sys_user.gmt_created is '创建时间';

comment on column mk_sys_user.gmt_modified is '修改时间';

comment on column mk_sys_user.create_by is '创建人id';

comment on column mk_sys_user.update_by is '更新人id';

comment on column mk_sys_user.is_delete is '0：正常 1：删除';

alter table mk_sys_user
    owner to postgres;

create index idx_mk_sys_user_username
    on mk_sys_user (username);

create table mk_sys_user_role
(
    user_id integer not null,
    role_id integer not null,
    primary key (user_id, role_id)
);

comment on table mk_sys_user_role is '用户角色表';

comment on column mk_sys_user_role.user_id is '用户ID';

comment on column mk_sys_user_role.role_id is '角色ID';

alter table mk_sys_user_role
    owner to postgres;

create table mk_user
(
    id            serial
        primary key,
    telephone     text      default ''::text          not null,
    password      text      default ''::text          not null,
    nickname      text      default ''::text          not null,
    head_portrait text      default ''::text          not null,
    gender        integer   default 0                 not null,
    province_id   integer   default 0                 not null,
    birthday      timestamp,
    gmt_created   timestamp default CURRENT_TIMESTAMP not null,
    gmt_modified  timestamp,
    is_delete     smallint  default 0                 not null
);

comment on table mk_user is '用户表';

comment on column mk_user.id is '主键,自增';

comment on column mk_user.telephone is '用户手机号';

comment on column mk_user.password is '用户密码';

comment on column mk_user.nickname is '用户昵称';

comment on column mk_user.head_portrait is '头像';

comment on column mk_user.gender is '性别 1：男 2：女 0：未知';

comment on column mk_user.province_id is '省';

comment on column mk_user.birthday is '生日';

comment on column mk_user.gmt_created is '创建时间';

comment on column mk_user.gmt_modified is '修改时间';

comment on column mk_user.is_delete is '0：正常 1：删除';

alter table mk_user
    owner to postgres;

create index idx_mk_user_gmt_created
    on mk_user (gmt_created);

create index idx_mk_user_nickname
    on mk_user (nickname);

create index idx_mk_user_telephone_nickname
    on mk_user (telephone, nickname);

